In [ ]:
#Líneas de numpy con una sola dimension

In [10]:
import numpy as np
a=[0,1,2,3,4,5]

#crear un array de numpy
x=np.array(a)
   

In [8]:
#verificar si es correcto con la función type

type(x)

numpy.ndarray

In [9]:
#verificar el tamaño de la línea

x.shape

(6,)

In [4]:
#el comando .dtype te dice el tupo de data que contiene una línea

x.dtype

dtype('int32')

In [5]:
#la media de la línea

x.mean()

2.5

In [7]:
#revisión de la versión de numpy

print(np.__version__)

1.22.4


In [9]:
#asignar otro valor al primer elemento de una línea, en este caso se modifica al valor 100

x[0]=100
x

array([100,   1,   2,   3,   4,   5])

In [10]:
#la asignación de que elemento elegir se coloca con el valor +1, es decir, si colocamos el número 4 estamos modificando la posición 5
x[4]=25
x

array([100,   1,   2,   3,  25,   5])

In [13]:
#Slicing: escoger que posiciones mostrar, se separan por un ":", el primer valor da la primera posición y el último (n-1) es hasta que posición muestra

d=x[2:5]  #se muestran la posiciones 2, 3 y 4
d

array([ 2,  3, 25])

In [14]:
#se puede modificar el valor de las posiciones aplicando un slicing

x[2:4]=200,300 #se modifica la posición 2 a 200 y la 3 a 300
x

array([100,   1, 200, 300,  25,   5])

In [18]:
#se puede imprimir bajo la siguiente metodología [empieza:termina:de cuanto en cuanto]
print(x[1:4:2])  #empieza en el 1, y termina en el 3 y se imprime de dos en dos

[  1 300]


In [19]:
#se puede imprimir desde el inicio hasta el lpimite que coloques

print(x[:5])

[100   1 200 300  25]


In [21]:
#o desde donde elijas, hasta su final

print(x[2:])

[200 300  25   5]


In [22]:
#ndim es la cantidad de lineas que existen en el codigo

x.ndim

1

In [23]:
#desviación estandar
x.std()

111.27356179953779

In [24]:
#valor max
x.max()

300

In [25]:
#valor min
x.min()

1

In [27]:
#funciones entre dos líneas (suma)

u=[1,2]
v=[2,5]

np.add(u,v)

array([3, 7])

In [28]:
#funciones entre dos líneas (resta)

u=[1,2]
v=[2,5]

np.subtract(u,v)

array([-1, -3])

In [30]:
#funciones entre dos líneas (multiplicacion)

u=[1,2]
v=[2,5]

np.multiply(u,v)

array([ 2, 10])

In [31]:
#funciones entre dos líneas (division)

u=[1,2]
v=[2,5]

np.divide(u,v)

array([0.5, 0.4])

In [32]:
#operación dot= se genera la multiplación de dos vectores y luego se suman sus valores

np.dot(u,v)

12

In [33]:
#se puede agrefar una constante

x+1

array([101,   2, 201, 301,  26,   6])

In [34]:
#valor pi
np.pi

3.141592653589793

In [35]:
#se puede calcular seno, coseno, etc

np.sin(x)

array([-0.50636564,  0.84147098, -0.8732973 , -0.99975584, -0.13235175,
       -0.95892427])

In [37]:
#crear una línea colocando los extremos y cuantos valores en total quieres que aparezan con el comando linspace

np.linspace(-2,3,num=5)

array([-2.  , -0.75,  0.5 ,  1.75,  3.  ])

In [38]:
#Lineas numpy 2D

In [11]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]

x=np.array(a) #crear una lista de dos dimensiones con np
x

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [12]:
x.ndim

2

In [13]:
x.shape


(3, 3)

In [14]:
x.size

9

In [16]:
#primer numero es la fila n+1 y segundo numero es la columna n+1

x[1,1]

22

In [17]:
#tmbn se puede hacer seprando en dos brackets

x[1][1]

22

In [18]:
#haciendo una combinación con slicing [row,column]

x[1,0:2]

array([21, 22])

In [19]:
x[0:1,2]

array([13])

In [20]:
#operaciones con lineas de dos dimensiones

In [21]:
#crear lista x

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [22]:
#crear lista y
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [25]:
#sumar dos lineas

z=X+Y
z

array([[3, 1],
       [1, 3]])

In [26]:
#ejemplo 1 multiplicacion

2*Y

array([[4, 2],
       [2, 4]])

In [27]:
#ejemplo 2 multiplicacion

X*Y

array([[2, 0],
       [0, 2]])

In [28]:
#comando dot

np.dot(X,Y)

array([[2, 1],
       [1, 2]])

In [29]:
z.T  #Transponer

array([[3, 1],
       [1, 3]])

In [30]:
#APIs & HTML

In [37]:
#se importa la librería requests la cual ayuda a enviar https entre dos softwares
import os 
from PIL import Image
from IPython.display import IFrame